version: '3'
services:
  go_web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "go run ./app/cmd/server/main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports: 
      - 8019:8019
    depends_on: 
      - "db"

  db:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: go_database
        MYSQL_USER: go_test
        MYSQL_PASSWORD: password
        TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
        - ./mysql/db-data:/var/lib/mysql
        - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3316:3306
      
volumes:
  db-data:
    driver: local